- blueprints/hoarder/docker-compose.yml
- fixes issue with meili search not starting
- adds necessary `MEILI_MASTER_KEY` env var to web service
> fix hoarder docker compose template

- blueprints/chatwoot/docker-compose.yml
Necessary upgrade to support linux/arm64, because the current (outdated) template doesn't support this architecture.
Makes the necessary changes to PostgreSQL to address breaking changes with Chatwoot. This is likely breaking for existing deployments. Unsure if Dokploy has a feature for template updates?
Tested on an arm64 instance with Dokploy v0.20.4.
> Push chatwoot to 4.0.3

- blueprints/kimai/docker-compose.yml
- meta.json
This pull request includes updates to the Kimai application version in both the Docker configuration and the metadata file.
Version updates:
* [`blueprints/kimai/docker-compose.yml`](diffhunk://#diff-a8c7f6562d76f8710e883260456e7c9aca26a902dbf0816ab748510cf5a4b37aL3-R3): Updated the Kimai Docker image from version `2.26.0` to `2.31.0`.
* [`meta.json`](diffhunk://#diff-61e02d96a75c79ab075606e62395cfebf1fc27a12f685dbd6acf7c9b108bb377L1224-R1224): Updated the Kimai version from `2.26.0` to `2.31.0`.
> chore: bump kimai version to 2.31.0

- blueprints/n8n/docker-compose.yml
- meta.json
This pull request includes updates to the `n8n` service version in the `docker-compose.yml` and `meta.json` files to ensure the use of the latest version.
Version updates:
* [`blueprints/n8n/docker-compose.yml`](diffhunk://#diff-8aec1d9f3a3ca0314b3d5940a5bf44fe932ec3b208e88e56c4128d0db0c4336fL4-R4): Updated the `n8n` service image version from `1.70.3` to `1.83.2`.
* [`meta.json`](diffhunk://#diff-61e02d96a75c79ab075606e62395cfebf1fc27a12f685dbd6acf7c9b108bb377L215-R215): Updated the `n8n` version from `1.70.3` to `1.83.2`.
> chore: bump n8n version to 1.83.2

- blueprints/budibase/docker-compose.yml
- meta.json
This pull request updates the Budibase application to a newer version in both the Docker configuration and the metadata file.
Version updates:
* [`blueprints/budibase/docker-compose.yml`](diffhunk://#diff-ea31c0f0430334063e2b9f98028556fd365d3c78a0a1563e90f63d8f191c50f6L3-R3): Updated the Budibase apps image version from `3.2.25` to `3.5.3`.
* [`meta.json`](diffhunk://#diff-61e02d96a75c79ab075606e62395cfebf1fc27a12f685dbd6acf7c9b108bb377L167-R167): Updated the Budibase version from `3.2.25` to `3.5.3`.
> chore: bump budibase to 3.5.3

- README.md
Think it's suppose to say `template.toml` rather than `template.yaml`. Let me know if it's otherwise
> fix: template files in README

- blueprints/beszel/docker-compose.yml
- meta.json
Update Beszel version to 0.10.2 in meta.json and docker-compose.yml
See changes for v0.10.2 -> [https://github.com/henrygd/beszel/releases/tag/v0.10.2](url)
> chore: update Beszel template to v0.10.2

- blueprints/qdrant/docker-compose.yml
- blueprints/qdrant/qdrant.svg
- blueprints/qdrant/template.toml
- meta.json
This commit introduces a functional template for one-click deployment of Qdrant on Dokploy.
The previous attempts to implement this template failed due to a missing environment variable: `SERVICE_FQDN_QDRANT_6333`.
This commit rectifies the issue by including this environment variable in the template configuration. The template has been tested and confirmed to deploy Qdrant correctly.
> feat: working Qdrant template

- meta.json
hovering over stack-auth is referencing uptime !
> fix(meta.json): stack-auth

- blueprints/formbricks/docker-compose.yml
This fix bumps the version of the Formbricks template to `3.1.5` from `3.1.3` to resolve #114 
The root cause of the issue is documented here: https://github.com/formbricks/formbricks/issues/4704
> Fix: Bump version of Formbricks template

- blueprints/pocketbase/docker-compose.yml
I recently submitted a PR for updated version of PocketBase template
Now I want to submit a correction of internal Docker path of my image
My image, in latest stage, uses /app WORKDIR. But this path was not included in previous PR. 
Here is the fix
> PocketBase template FIX mount path

- blueprints/formbricks/template.toml
See https://github.com/Dokploy/templates/issues/122
the idea is to generate a 32-char string [a-z][0-9] but not sure if there's a helper for that? perhaps we could add something like "randomString([a-z][0-9], 32)" or equivalent ?
> Fix Formbricks template

- blueprints/stalwart/docker-compose.yml
This commit updates the Docker image for the **stalwart** service.
Previously, the service was configured to use:
`stalwartlabs/mail-server:latest-alpine`
This has been changed to the correct image:
`stalwartlabs/stalwart:latest-alpine`
This change resolves an issue where the incorrect image name was being used, ensuring the service utilizes the intended Stalwart mail server image.
Also add a comment recommending to use specific version tags for production environments.
> chore: update stalwart mail server image to resolve an issue

- blueprints/rybbit/docker-compose.yml
- blueprints/rybbit/template.toml
- meta.json
Changes:
- remove /api stripping
- remove caddy reverse proxy
- added clickhouse config in volume mount
Release notes:
- https://github.com/rybbit-io/rybbit/releases/tag/v1.0.0
Migration guide:
- https://www.rybbit.io/docs/v1-migration
> fix(blueprint): rybbit v1.2.0

- blueprints/outline/template.toml
Outline expects a hex-encoded 32-byte random `SECRET_KEY` value, but currently a `base64:32` value is generated, making authentication impossible. 
[outline/.env.sample](https://github.com/outline/outline/blob/6a16dc07c154712fbe0ff2cf254a8f8ee97ad4f6/.env.sample#L25-L27)
```
SECRET_KEY=generate_a_new_key
```
```json
{"error":"Invalid key length","level":"error","message":"Failed to encrypt database column (accessToken). The SECRET_KEY environment variable is not the correct length.","stack":"RangeError: Invalid key length\n    at Cipheriv.createCipherBase (node:internal/crypto/cipher:121:19)\n    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:140:3)\n    at new Cipheriv (node:internal/crypto/cipher:243:3)\n    at Object.createCipheriv (node:crypto:147:10)\n    at …
```
> fix(blueprint): generate required 32-byte hex secret_key with hash:64

- blueprints/gotenberg/docker-compose.yml
Too verbose + takes up space when enabled
> fix(blueprint): disable healthcheck logging for gotenberg

- blueprints/pocketbase/docker-compose.yml
This pull request updates the Docker image used for the `pocketbase` service in the `docker-compose.yml` file to a new repository and tag.
* [`blueprints/pocketbase/docker-compose.yml`](diffhunk://#diff-ad9bfe816b50dd6599dca88c3c5130e80aa8153ed872e45c8734c8f91e1d573cL4-R4): Changed the `pocketbase` service image from `docker.io/bakirg/pocketbase-docker:0.28.0` to `ghcr.io/muchobien/pocketbase:latest`.Change the Pocketbase Docker image to a working version in the compose file.
> Update Pocketbase docker-compose.yml

- blueprints/wordpress/docker-compose.yml
volumes:
**_- ./wp-app:/var/www/html_**
- ../files/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
when you use the volume like this, wp-app folder is generated inside /code folder. The code folder is wiped out after reloading but not deploying/redeploying.
After reloading since the wp-app folder is gone there is no way to access the app.
> Reload causing wp-app to be removed because of the folder path. [Wordpress Template]

- blueprints/n8n/docker-compose.yml
- meta.json
This pull request includes updates to the n8n service version in the docker-compose.yml and meta.json files to ensure the use of the latest version.
> chore: bump n8n version to 1.104.0

- blueprints/plane/docker-compose.yml
- meta.json
- Bumped all makeplane service images from v0.25.3 to v0.27.1
- Updated web, space, admin, live, api, worker, beat-worker, migrator and proxy services
- Version alignment for all plane components in docker-compose blueprint
New PR of Plane
- [v] I have read the suggestions in the README.md file https://github.com/Dokploy/templates?tab=readme-ov-file#general-suggestions-when-creating-a-template
- [v] I have tested the template in my instance (4vcpu 8 GB RAM VPS), so the maintainers don't spend time trying to figure out what's wrong.
- [v] I have added tests that demonstrate that my correction works or that my new feature works.
Close automatically the related issues using the keywords: `closes #ISSUE_NUMBER`, `fixes #ISSUE_NUMBER`, …
> chore(blueprint): update plane services to v0.27.1

- blueprints/invoiceshelf/docker-compose.yml
- blueprints/invoiceshelf/template.toml
Invoice shelf docker images dont have the `latest` tag for some reason which the current template references, the closest to it is `nightly`, so we can switch to it
https://hub.docker.com/r/invoiceshelf/invoiceshelf/tags
> Fix invoiceshelf docker image tag

- blueprints/signoz/docker-compose.yml
Signoz template are missing this environment variable:
`      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz`
> fix: add signoz alertmanager provider in the template

- app/public/blueprints
- blueprints/ojs/docker-compose.yml
- blueprints/ojs/ojs.svg
- blueprints/ojs/template.toml
- meta.json
Adds a complete Open Journal Systems (OJS) template for researchers, educational institutes, and journal publishers.
- **OJS 3.3.0-21** with MariaDB 11.4 database
- **Custom SVG logo** and proper template metadata
- **Environment variables** for secure database configuration
- **Domain setup** ready for custom domains
- **Persistent storage** for database, files, and configuration
- Uses official `pkpofficial/ojs:3_3_0-21` Docker image
- Auto-generated secure passwords for database
- Proper volume management for data persistence
- Follows Dokploy template best practices
- publishing, journal, research, academic
- GitHub: https://github.com/pkp/docker-ojs
- Website: https://pkp.sfu.ca/ojs/
- Docs: https://pkp.sfu.ca/ojs/docs/
- Template deploys successfully without Docker errors
- Logo …
> Add Open Journal Systems (OJS) template #348

- blueprints/browserless/docker-compose.yml
- blueprints/browserless/template.toml
Updates browserless template with:
- Docker image: v2.23.0 → latest
- Fix typo: BROWERLESS_HOST → BROWSERLESS_HOST  
- Standardize port: 3_000 → 3000
Fix -#418
> fix(browserless): update image to latest and fix configuration issues
