app/index.html, app/package.json, app/pnpm-lock.yaml, app/src/components/TemplateGrid.tsx, app/src/components/ui/dialog.tsx, app/src/components/ui/label.tsx, app/src/components/ui/tabs.tsx, app/src/store/index.ts
=> chore(ui): improve template dialog

app/package.json, app/pnpm-lock.yaml, app/src/App.tsx, app/src/components/Search.tsx, app/src/components/SelectedTags.tsx, app/src/components/TemplateGrid.tsx, app/src/components/ui/code-editor.tsx, app/src/components/ui/dialog.tsx, app/src/store.ts
- Added (List/Grid) view
- Added skeleton for each during loading
- other ui improvements
=> chore(ui): improve search UI

.github/workflows/build-preview.yml, .github/workflows/deploy-preview.yml
- Renamed job to "Build Preview Deployment" and adjusted concurrency settings.
- Streamlined steps by removing unnecessary permissions and comments.
- Updated pnpm action to the latest version and ensured Node.js setup is consistent.
- Removed deployment step to Cloudflare Pages and related verification steps for simplification.
=> refactor: update build preview workflow for clarity and efficiency

blueprints/vaultwarden/docker-compose.yml, meta.json
- Update template to latest version that will fix many security holes
=> vaultwarden template update (security fixs)

blueprints/superset/docker-compose.yml
The `test` command was incorrectly using the postgres healthcheck.
=> Fix superset redis healthcheck

blueprints/minio/docker-compose.yml, blueprints/minio/template.toml
- add random password generation
- forward port 9000 and expose 9001 through traefik
- add some comments to add some volume setting info
=> ♻️ Refacto minio template

blueprints/listmonk/docker-compose.yml, blueprints/listmonk/template.toml
Also simplify the listmonk install process.
=> Upgrade Listmonk to v5.0.0

blueprints/pocketbase/docker-compose.yml, blueprints/pocketbase/template.toml, meta.json
- template configuration files and metadata
- change source repository of PocketBase Docker image
- I wanted to try out the PocketBase template and noticed it is outdated
- I changed source of Docker image to my repository, since I plan to update it regularly (haven't thought a way to automate it - yet!)
___I request you to thoroughly inspect both changes to this repo, and my `pocketbase-docker` project, since I'm still a learner/inter, and I don't want to cause trouble with my poor approach. Bust most importantly - I want to learn!___
=> update pocketbase to 0.27.2

blueprints/pocketbase/docker-compose.yml, meta.json
introduced new pocketbase version
=> bump PocketBase version to 0.28.0

blueprints/convex/docker-compose.yml
Convex version bump. Without this convex auth fails as seen here https://github.com/get-convex/convex-auth/issues/215
=> Convex version bump

blueprints/rybbit/docker-compose.yml
From PR: https://github.com/rybbit-io/rybbit/pull/261
=> feat(blueprint): healthcheck added for rybbit backend service

blueprints/appwrite/docker-compose.yml, meta.json
Upgrades the Appwrite template from version 1.6.0 to 1.6.1.
=> chore(appwrite): bump version to 1.6.1

blueprints/trmnl-byos-laravel/docker-compose.yml
Updates trmnl-byos-laravel template to version 0.4.0
=> feat(blueprint): update trmnl-byos-laravel template

blueprints/minio/docker-compose.yml
- Added the last image version of Minio as a comment, before they remove most of the admin ui.
=> Updated Minio docker-compose.yml

meta.json
- Introduced a new entry for GitLab Community Edition, including a detailed description, logo, and relevant links.
- Reformatted tag lists for consistency across all entries.
New PR of [Template Name]
=> Add GitLab CE entry to meta.json

blueprints/rybbit/docker-compose.yml, meta.json
Bump rybbit version from 1.2 to 1.5
=> chore(blueprint): update rybbit to v1.5

blueprints/autobase/docker-compose.yml, meta.json
Autobase 2.3.0 released
https://github.com/vitabaks/autobase/releases/tag/2.3.0
Close automatically the related issues using the keywords: `closes #ISSUE_NUMBER`, `fixes #ISSUE_NUMBER`, `resolves #ISSUE_NUMBER`
Example: `closes #123`
=> Update Autobase to v2.3.0

meta.json
1. Updating the outdated links.
2. Enter the correct link (for Checkmate).
=> Update outdated links

blueprints/excalidraw/docker-compose.yml
Added healthcheck for excalidraw. Also remove deprecated docker compose version.
=> feat(blueprint): healthcheck for excalidraw

meta.json
I have updated the links for Gitingest, Kuno and Tianji templates.
=> Update links for templates

blueprints/plark/docker-compose.yml
(Fix): Setting pull policy to always to pull the latest version of _plark_ service
=> (fix): set pull policy to pull latest image

blueprints/kestra/docker-compose.yml
the password must be 8 characters with one capital letter, one digit and one special character
=> Change basic auth password for Kestra

meta.json
Update metadata for [bytestash](https://github.com/jordan-dalby/ByteStash) as it was outdated
=> Update metadata for bytestash
